### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by massayoshi** [nagytech/scythe-online-automa#1]
Hey Jonathan!

I don't know how we can go on with these, but here are the icons.

https://github.com/massayoshi/scythe-online-automa/commit/d977a678d7a265dd0cb661a70661062ba6de2b3c

**Comment by nagytech** [comment]
Awesome thanks.  If I have to refactor in order to use them I'll get to it this weekend.

**Comment by massayoshi** [comment]
I will take a closer look at your code to see if I can help.

**Comment by nagytech** [comment]
Hey Flávio:

Thanks again for the assets folder.

I've updated the icons.png file a bit so that it will work for me.  There were also some combined icons that were missing, so I added them to the end.

The movement/gains/recruit areas of the card now render with icons, including the factions.

I might use the river isolation and phase icons later on as well, but I'm happy with it for now.

![image](https://cloud.githubusercontent.com/assets/8542033/17274107/99284330-5713-11e6-87fe-9c2bc8678055.png)

**Comment by massayoshi** [comment]
That's really nice!

One question, though. Do you have already your physical Automa deck or did you get everything from the PnP files? Cause I'm still waiting my copy and I was comparing some of the cards and found some differences like this one below. I should mention that I haven't really understood how to read the cards so I might be wrong.

![automa-card](https://cloud.githubusercontent.com/assets/609562/17275227/c5a6f83a-56d6-11e6-831d-e192bef45478.jpg)

![screen shot 2016-07-31 at 4 25 30 am](https://cloud.githubusercontent.com/assets/609562/17275229/da15ddea-56d6-11e6-8f04-b31265bf71f1.png)

**Comment by nagytech** [comment]
I’ve got my own deck, but I used the PnP files to make the JSON model.

There looks to be a few inconsistencies, so I’ll go through and double check everything again.

**Comment by nagytech** [comment]
I had a look through the JSON model, and it looks correct.  It just seems the rendering is a bit off.  So, I've made the following changes:

- taken out the 'move' icon before the 'factory/encounter' icon.
- added the enlist icon before the enlist bonus.
- replaced the 'character' icon with the 'character/mech' icon on the Gains panel.

![image](https://cloud.githubusercontent.com/assets/8542033/17276814/ea83211a-5776-11e6-9169-db09432e314c.png)

**Comment by nagytech** [comment]
Can probably close this now.
